### ISSUE TITLE
Unterstützung von gzip und Caching für Dateianhänge soll nicht zwingend sein 

### ISSUE THREAD

**Issue by lu-j** [OParl/specs#276]
Auf dem Workshop wurde beschlossen:
HTTP-Kompression (gzip) und Caching für Dateianhänge soll nicht mehr zwingend, sondern nur empfohlen sein, da beides nicht unbedingt notwendig, aber schwer zu realisieren ist. Gzip wird in der Regel vom Webserver oder einem Reverse Proxy übernommen. Wir wollen aber vermeiden, dass für OParl die Serverkonfigurationen der Kommunen angepasst werden müssen. Dateianhänge werden wahrscheinlich nicht vom Webserver, sondern von der RIS-Software ausgeliefert, damit die Zugriffsberechtigung geprüft werden kann. Caching muss vermutlich erst in die RIS-Software implementiert werden, was eine unnötig hohe Anforderung wäre.

Wir bitten um Feedback!

**Comment by akuckartz** [comment]
Nach aktuellem Stand wird OpenGovLD auch keine Kompression zwingend fordern (weder für Server noch für Clients).

**Comment by akuckartz** [comment]
Was genau ist mit "Caching für Dateianhänge" gemeint? Was soll dazu geändert werden?

**Comment by lu-j** [comment]
Mit Caching für Dateianhänge ist Conditional GET gemeint, die Anforderung in den Kapiteln 4.8.3 und 4.8.4.

In folgendem Fall ist Conditional GET nützlich:
Jemand schreibt eine Webanwendung mit OParl Daten und möchte aus Speicherplatzgründen die Dateianhänge nicht auf den eigenen Server laden. Stattdessen werden nur die Links gespeichert, damit die User die Dateien direkt vom RIS-Server laden (Hotlinking). Öffnet ein User beispielsweise eine PDF Datei (ohne sie zu speichern) und öffnet sie danach ein zweites mal, muss sie ein zweites Mal vom Server geladen werden. Unterstützt der Server aber Conditional GET, kann der Browser anfragen, ob die Datei zwischenzeitlich verändert wurde und der Browser kann die Datei gegebenenfalls aus dem Cache laden. Es ist also eine nützliche Funktion, wird aber aktuell nicht von allen RIS-Systemen unterstützt und ich denke der Aufwand für die Implementierung ist unnötig hoch, daher soll Conditional GET empfohlen aber nicht zwingend sein.

Möchte man die Dateianhänge von einem OParl-Server auf einen eigenen Server laden, benötigt man Conditional GET nicht. Der "modified" Timestamp des zugehörigen File-Objekts muss sich aktualisieren, sobald sich eine Datei verändert hat. Daran erkennt man, welche Dateien geändert wurden und nochmal heruntergeladen werden müssen.

**Comment by akuckartz** [comment]
Es geht also um die Behandlung von Zugriffen auf Dateien, also nichts, was RIS-spezifisch wäre.

Im Entwurf der Spezifikation stand und steht:
~~~
Für einen OParl-Server wird EMPFOHLEN, die nachstehenden Varianten des
Conditional GET zu unterstützen:

-   If-Modified-Since: Der Client sendet mit der Anfrage als Bedingung
    ein Datum. Nur wenn die angefragte Datei zuletzt nach diesem Datum
    geändert wurde, wird der Dateiinhalt mit der Antwort ausgeliefert.

-   If-None-Match: Erlaubt die Formulierung der Bedingung anhand eines
    Entity-Tags.
~~~

Insofern wurde keine Änderung besprochen, sondern schlicht der bisherige Stand bestätigt.

RIS-Hersteller und -Betreiber sind aber aus verschiedenen Gründen gut beraten, wenn sie Caching auf möglichst gute Weise unterstützen.

- Es wird möglicherwiese öffentlich zugängliche technische Angaben und Statistiken zu RIS-Systemen geben. Seltsamkeiten von http-Implementierungen könnten automtaisch ermittelt und erwähnt werden (als eine Art offener technischer Meta-Daten). Wenn jemand einen Tipp für geeignete Software hat: her damit!

- Ein angemessenes Verhalten eines http-Servers würde ich jedenfalls erst einmal voraussetzen. Wenn das dazu führt, dass der Datentransfer aufgrund technischer Unzulänglichkeiten des Servers in die Höhe geht, dann sind Beschwerden beim Hersteller oder Betreiber vorprogrammiert. Ich halte es für zweifelhaft, dass ein RIS "modified" Properties richtig behandelt, wenn noch nicht mal der normale http-Zugriff sauber implementiert ist.

- Suchmaschinen werden auch ihre Schwierigkeiten mit schlecht implementierten http-Servern haben.

**Comment by akuckartz** [comment]
Im Spezifikationsentwurf steht aber bisher auch dies:
~~~
Die Auslieferung eines Last-Modified-Headers gilt für alle OParl-Server
beim Zugriff auf eine Datei-URL, sei es Download- oder Zugriffs-URL, als
ZWINGEND.
~~~
Zu "Last-Modified" siehe https://tools.ietf.org/html/rfc7232#section-2.2

**Comment by the-infinity** [comment]
Fixed by https://github.com/OParl/specs/commit/2ba5a2f3b2dd60606ec14cf0daee0c26b427bbee (Last-Modified nur noch empfohlen).
